### ISSUE TITLE
"java.format.settings.google.extra": "--aosp" (For 4 instead of 2 spaces) doesn't seem to work

### ISSUE THREAD

**Issue by vorburger** [JoseVSeb/google-java-format-for-vs-code#12]
I've added the following ([here](https://github.com/enola-dev/enola/blob/5f7f8b7edc8200d17fa2efbcc365a6d3e91a2453/.vscode/settings.json#L43)):

    "java.format.settings.google.extra": "--aosp", // For 4 instead of 2 spaces!

but it seems to ignore this? (It's formatting with 2 instead of 4 spaces.) Am I misunderstanding what the documentation means by _"Extra CLI arguments to pass"?_

**Comment by JoseVSeb** [comment]
> but it seems to ignore this? (It's formatting with 2 instead of 4 spaces.) Am I misunderstanding what the documentation means by _"Extra CLI arguments to pass"?_

changes to configuration needed restarting to take effect. I have updated the code to get the configuration directly from settings when the formatter is invoked.

**Comment by vorburger** [comment]
@JoseVSeb thanks for the prompt reaction and attempted fix, but somehow this still doesn't seem to work, for me, even after upgrading to `v1.0.1` ... with #13 (thanks!) we can now see that, on a project with the aforementioned configuration, it still does:

```
2024-02-09 14:48:18.073 [debug] > java -jar /home/vorburger/.vscode/extensions/josevseb.google-java-format-for-vs-code-1.0.1/cache/google-java-format-1.19.2-all-deps.jar --lines 1:47 -
2024-02-09 14:48:18.074 [info] Formatting completed in 529ms.
``` 

so, somehow, it apparently still does not "pass through" `--aosp`?

**Comment by vorburger** [comment]
> @vorburger it worked fine for me... 🤔 strange.

@JoseVSeb I created a simple reproducer project, to see if we can figure out why this works for you, but still not for me:

In https://github.com/vorburger/LearningBazelJavaVSC/, it works, as you say; with [a simple `settings.json`](https://github.com/vorburger/LearningBazelJavaVSC/blob/develop/.vscode/settings.json).

In https://github.com/enola-dev/enola it does not work; but that project has [a complicated long `settings.json`](https://github.com/enola-dev/enola/blob/main/.vscode/settings.json).

If you copy/paste the 2nd (enola) project's Settings JSON into the simple 1st (LearningBazelJavaVSC) one, can you also reproduce it, like I can?

There is clearly SOMETHING in that 2nd JSON which is throwing your extension off - but I cannot figure out what it is...

**Comment by vorburger** [comment]
Oh, I just figured it out - I think; it seems to be because of this:

```json
  "[java]": {
    "editor.defaultFormatter": "josevseb.google-java-format-for-vs-code",
  },
  "java": {
    "completion.favoriteStaticMembers": ["com.google.common.truth.Truth.*"]
  }
```

Looks like the latter is "overridden" (shadowing, hiding) the former!

Is this expected and correct VSC behavior? I had assumed that these mean 2 different things; I thought that:

* `[java]` key configures Settings for `*.java` files
* `java` allowed "grouping" `java.*` settings

Perhaps this is not so and I misunderstand VSC configuration?

**Comment by vorburger** [comment]
Fixed in https://github.com/enola-dev/enola/pull/463 - all good now! (And sorry for my "noise" here.)
